version: "3.8"

services:
  server:
    image: pern-store-server
    container_name: pern-store-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=pernstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminuser
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9000:9000
    networks:
      - pernstore
    depends_on:
      - database

  client:
    image: pern-store-client
    container_name: pern-store-client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - server
    networks:
      - pernstore

  database:
    image: postgres:15-alpine
    container_name: pern-store-db
    restart: always
    environment:
      - POSTGRES_DB=pernstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminuser
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pernstore

  pgadmin:
    image: dpage/pgadmin4
    container_name: pern-store-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - pernstore

networks:
  pernstore: 
    driver: bridge

volumes:
  db:
    driver: local