sonar.projectKey=Pern-Store
sonar.projectName=Pern-Store
sonar.projectVersion=1.0
sonar.sources=./client,./server
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

# Exclude non-Node.js files, such as tests, build directories, node_modules, CSS, HTML, etc.
sonar.exclusions=**/node_modules/**,**/test/**
# Enable JavaScript analysis (for Node.js)
sonar.language=js  # or 'ts' for TypeScript projects

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info